import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { ChakraProvider } from '@chakra-ui/react';
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import { Suspense } from 'react';
import Loading from './loading';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Head>
          <title>Real Estate</title>
        </Head>
        <body className={inter.className} >
          <ChakraProvider >
            <header>
              <MainMenu />
            </header>
           
              {children}
          
            <footer>
              <Footer />
            </footer>
          </ChakraProvider>
        </body>

      </html>
    </>

  );
}
